version: "0.1"
environments:
  - name: feature/flycode-configuration-7z006nn
    branch: feature/flycode-configuration-7z006nn
    mode: pull-request
apps:
  - name: charts
    path: ""
    text-resources:
      - path: charts/src/assets/en-Us.json
        format: nested-key-value
  - name: flyhl
    path: ""
    text-resources:
      - path: src/assets/en-Us.json
        format: nested-key-value
