version: "0.1"
environments:
  - name: master
    branch: master
    mode: Ignore
apps:
  - name: chrt221
    path: ""
    text-resources:
      - path: src/assets/*.json
        format: nested-key-value
