version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: chrt
    path: ""
    text-resources:
      - path: src/assets/*.json
        format: nested-key-value
