version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: chrt1
    path: ""
    text-resources:
      - path: src/assets/*.json
        format: nested-key-value
