version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
  - name: feature1
    branch: feature/flycode-texts-1-rh006np
    mode: pull-request
apps:
  - name: charts
    path: ""
    text-resources:
      - path: src/assets/en-Us.json
        format: nested-key-value
