version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: charts
    path: ""
    text-resources:
      - path: charts/src/assets/en-Us.json
        format: nested-key-value
