version: "0.1"
environments:
  - name: main22
    branch: main
    mode: pull-request
  - name: config
    branch: feature/flycode-configuration-7z006nn
    mode: pull-request
apps:
  - name: chrt
    path: ""
    text-resources:
      - path: src/assets/*.json
        format: nested-key-value
